#include "motors_hw.h"

void motorsHwInit()
{
  MOTOR_AZ_EN_DDR_REG |= MOTOR_AZ_EN_PIN;
  MOTOR_AZ_R1_DDR_REG |= MOTOR_AZ_R1_PIN;
  MOTOR_AZ_R2_DDR_REG |= MOTOR_AZ_R2_PIN;

  MOTOR_EL_EN_DDR_REG |= MOTOR_EL_EN_PIN;
  MOTOR_EL_R1_DDR_REG |= MOTOR_EL_R1_PIN;
  MOTOR_EL_R2_DDR_REG |= MOTOR_EL_R2_PIN;
}
